### ISSUE TITLE
On image file

### ISSUE THREAD

**Issue by John-Ge** [baaivision/DenseFusion#1]
I find it's difficult to download the images in the datasets. When would you like to release the images?

**Comment by lixiaotong97** [comment]
Due to image copyright issues, we have currently only released the URLs of the images and the download script. Thanks for your advice, we are considering if there is a better way to address this issue.

**Comment by lixiaotong97** [comment]
Hi, the image zips are uploading to Huggingface and it will take some time (>100GB).

**Comment by lixiaotong97** [comment]
We have uploaded all the image zips to HuggingFace. It will be more convenient to access and explore the dataset.
