### ISSUE TITLE
The Release of Visual Expertise Results

### ISSUE THREAD

**Issue by cxmscb** [baaivision/DenseFusion#2]
Thank you for sharing your work！！！I wonder if the intermediates(i.e., the visual expertise results) will be released soon?

**Comment by lixiaotong97** [comment]
Thanks for your attention! We have only released the final merged captions and currently have no plans to release the intermediate steps.

**Comment by swearos** [comment]
@lixiaotong97 About the use of OWL-ViTv2, is it used like this:
Using the result of RAM++, tagging word as a query for calling open-set detection?

**Comment by lixiaotong97** [comment]
Yes, we use the tagging words as the vocabulary. For more details, you can refer to Section 3.2.1 of the paper.
