### ISSUE TITLE
About the images

### ISSUE THREAD

**Issue by Coobiw** [baaivision/DenseFusion#3]
Hi, thanks for your great work! I want to know how can I get the images if I have downloaded LAION-2B? Can I use `image-id` to locate it? Thanks for your advice or reply!

**Comment by lixiaotong97** [comment]
If you have the LAION-2B dataset, you can filter the corresponding images using the provided URL information through a set, and the entire process can be completed quickly. Since we have rehashed the data, the image IDs are not completely identical.

**Comment by lixiaotong97** [comment]
We have uploaded all the image zips to HuggingFace. It will be more convenient to access and explore the dataset.

**Comment by xin-ran-w** [comment]
Hello, I have a question about the 100K image, there is an image path `DenseFusion-4V-100K/000045/1002078010534.png`, but no 000045.zip in the huggingface repo, is there something wrong? How should these image files be placed? And some image files seem corrupt.
```
PIL.UnidentifiedImageError: cannot identify image file '.../DenseFusion-1M/images/DenseFusion-4V-100K/000043/3328617021737.png'
```
